### ISSUE TITLE
built-in process management

### ISSUE THREAD

**Issue by untitaker** [pr2502/ra-multiplex#1]
in order for this to be a full drop-in replacement it could be cool to:

1. start `ra-multiplex-server` if it's not already running from within `ra-multiplex`
2. have `ra-multiplex-server` shut down if it no longer holds any rust-analyzer instances

**Comment by oysols** [comment]
This functionality can be emulated by starting the server automatically every time you open your editor.
Since it is trying to bind to the same port, it will just silently fail if there is already a server running.

Using Vim:
```vim
if executable('ra-multiplex-server')
    autocmd FileType rust silent !(&>/dev/null ra-multiplex-server &)
endif
```

**Comment by pr2502** [comment]
Just wanted to note that I tried to implement the original proposal but haven't finished anything yet because there isn't any cross-platform solution for daemonizing processes.

The crate [daemonize](https://crates.io/crates/daemonize/) seems to be the most portable way of implementing this at least on unix-like OSs, but it requires me to split the implementation from other platforms and forces me to tackle and decide on things that should be left for other process management tools, like where to log.

While I understand the appeal of the convenience this feels very out-of-scope for `ra-mux-server`, I'd consider a `systemd` user unit as a betterreplacement for most unix systems. Adding an example how to configure that in the documentation would be my prefered solution.

**Comment by yaymukund** [comment]
Here's what I'm using:
```ini
[Unit]
Description=Rust analyzer multiplexer server

[Service]
Type=simple
ExecStart=/usr/bin/ra-multiplex-server
Restart=always
RestartSec=5s

[Install]
WantedBy=default.target
```
