### ISSUE TITLE
Remove workspace detection?

### ISSUE THREAD

**Issue by untitaker** [pr2502/ra-multiplex#17]
coc-rust-analyzer at least sends the LSP client CWD to be equal to its own autodetected workspace root. VSCode does the same AFAIK.

This doesn't cause any problems but makes it hard for me to debug issues related to workspace detection, because there are now three layers that try to figure out where Cargo.toml is: coc.nvim, this proxy and rust-analyzer.

Is there an LSP client that does not do this sort of workspace detection on its own? If so, would you still accept a PR that allows me to disable this behavior and always use client_cwd?

**Comment by untitaker** [comment]
For my own reference, the issue i was trying to debug is described in https://github.com/neoclide/coc.nvim/issues/4554#issuecomment-1484221267

**Comment by pr2502** [comment]
Sorry for late reply. I believe coc-rust-analyzer didn't handle it correctly and would spawn the LSP server in the same working directory vim was spawned from. Maybe they've fixed it since but I'd still like to leave the option in for other simple LSP clients so I've instead made it a configurable variable in #19 and left it on by default since it shouldn't cause any harm. Does this resolve the issue for you?

**Comment by untitaker** [comment]
@pr2502 I have given up on investigating this issue and am overriding workspace detection on coc-rust-analyzer side, but I believe I might have a use for this configurability in the future when i'm moving to neovim's own lsp. but for now I don't need any changes anymore.
