### ISSUE TITLE
duplicate DidOpenTextDocument

### ISSUE THREAD

**Issue by qustavo** [pr2502/ra-multiplex#44]
I'm using ra-multiplexer with neovim and lsp.
It all works fine when I open a new project for the first time. After closing and re-opening the editor (neovim) `ra-multiplexer` logs the following error:

```
[ERROR] [/my/project 1558707] [ERROR rust_analyzer::handlers::notification] duplicate DidOpenTextDocument: /my/project/src/main.rs
```

Everything seems to be working fine, but inlay_hints just disappear. Not sure if it's a ra-multiplexer bug or not.

**Comment by pr2502** [comment]
If the issue is in a workflow like open file A -> close editor with file A -> open file A again. Then it sounds like a bug with neovim's LSP implementation because it never sent the corresponding Close notification, assuming the server was going to close anyway so why bother with cleanup.

Docs here <https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#textDocument_didOpen>

However we might want to support opening the same file from multiple neovim instances at once at which point we'd have to explicitly handle this even if neovim was behaving properly because we'd have to silence the second Open and the first Close.

**Comment by qustavo** [comment]
I see, thanks!
Wouldn't it make sense for ra-multiplex to send the close notification upon client disconnection?

**Comment by pr2502** [comment]
Yes, we could implement workarounds for misbehaving clients, I'm not opposed to it. We already implement some workarounds for the init messages.
