### ISSUE TITLE
`--ra-mux-server` argument applies to `ra-multiplex` and not `ra-multiplex-server`

### ISSUE THREAD

**Issue by yaymukund** [pr2502/ra-multiplex#9]
Thank you for building this crate. It's very handy.
### Problem
```bash
$ ra-multiplex-server --ra-mux-server /path/to/custom/rust-analyzer &
$ ra-multiplex <...>
```
then I get:
```
[INFO ] [32830] client connected
[ERROR] [32830] client error: spawn ra instance

     Caused by:
         0: couldn't spawn rust-analyzer
         1: No such file or directory (os error 2)
```
Passing `--ra-mux-server` to `ra-multiplex-server` doesn't seem to work. `ra-multiplex` cannot find `rust-analyzer`.

### Solution

You have to pass it via the *client*. To fix:
```bash
$ ra-multiplex-server --ra-mux-server /path/to/custom/rust-analyzer &
$ ra-multiplex --ra-mux-server /path/to/custom/rust-analyzer <...>
```
### Thoughts

1. Does passing `--ra-mux-server` to the server do anything?  If not, should it error?
2. If `--ra-mux-server` *is* a valid option to the server: In the absence of a client `--ra-mux-server`, the server's configuration should take priority.  
3. Maybe we could pass `ra-mux-server` via the config?
4. Maybe this could be spelled out a bit more in the docs? We could kill two birds with one stone by adding a `--help`?

I am happy to submit PRs for any/all of these. I just wanted to ask first because the intended/correct behavior aren't clear to me.

**Comment by pr2502** [comment]
Hi,

1. yes this is the intended behaviour. Setting the LSP server for the whole server wouldn't make sense since one ra-mux-server instance is meant to support any LSP server, it's meant to be configured by the LSP client (as is shown in the examples), this allows you to use multiple LSP servers concurrently from multiple LSP clients (say rust-analyzer from one workspace and clangd from another).

2. Definitely, I was trying to keep the cli trivial but erroring on unexpected input would be nice. I'm working on a big rewrite of the cli while trying to implement #1 but that's probably ways off as I don't have much time, so adding the error in the meantime sounds like a good idea.

3. Suggestions for the docs are welcome. I could've omitted something that felt obvious to me even though it isn't to others.

Also looking at the error message you've attached, it's missing the path ra-mux attempted to open, I'd also like to fix that.

**Comment by yaymukund** [comment]
Okay, I'll see if I can put something together this week/weekend.
